version: '3.8'

services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    secrets:
      - mariadb_root_password
      - mariadb_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - intra
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    secrets:
      - mariadb_password
    volumes:
      - wp_files:/var/www/wordpress
    networks:
      - intra
    depends_on:
      - mariadb
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - wp_files:/var/www/wordpress
    networks:
      - intra
    depends_on:
      - wordpress
    restart: always

networks:
  intra: {}

volumes:
  db_data:
    driver_opts:
      type: none
      device: /home/jcamuenh/data/mariadb
      o: bind
  wp_files:
    driver_opts:
      type: none
      device: /home/jcamuenh/data/wordpress
      o: bind

secrets:
  mariadb_root_password:
    file: ./requirements/mariadb/secrets/mariadb_root_password.txt
  mariadb_password:
    file: ./requirements/mariadb/secrets/mariadb_password.txt